name: Publish
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
                token: ${{ secrets.BOT_TOKEN }}
                fetch-depth: 0
          - uses: actions/setup-node@v4
          - run: npm install
          - run: npm run test
          - name: Semantic Release
            uses: cycjimmy/semantic-release-action@v3
            if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
            env:
                GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
